### ISSUE TITLE
As a user, I want the permit guidelines to be shorter and easier to read to minimize page scrolling.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#196]
## Notes
This is an issue that has appeared in several usability studies:

[Sprint-04-Christmas-tree-ePermit-research-results---November-22-2017](https://github.com/nciinc/fs-intake-module/wiki/Sprint-04-Christmas-tree-ePermit-research-results)
[Sprint-05---Christmas-tree-ePermit-research-results---December-12,-2017](https://github.com/nciinc/fs-intake-module/wiki/Sprint-05---Christmas-tree-ePermit-research-results---December-12,-2017)

## Acceptance Criteria
- [ ] Tighten the language to shorten overall page length
- [ ] Explore design options and graphics to make the content easier to read

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by JaneZC** [comment]
@ASprinkle @MelissaBraxton 

Do we need a legal review of the rules content on the order page? I think a plain language version is probably fine on the tree guidelines page, but I am wondering if lawyers would okay a rules to know section on the order page (especially with a checkbox).

**Comment by MelissaBraxton** [comment]
Thanks for raising this Jane. We have been operating under the assumption
that this will qualify as a non-substantial form change under OMB, but
FS/TTS will need to submit a non-substantial form change request (with
screen shots of the permit form and the permit itself) to in the coming
weeks. This is currently a card in the TTS backlog.

Melissa Braxton
User Experience Designer, 18F
Cell: (415) 696-4216
https://18f.gsa.gov/

**Comment by ASprinkle** [comment]
As per the need for a legal review for the change in process (check box vs. hard copy signature) - I am not sure how to respond to that.
The rules content for Christmas tree harvest has been compiled from existing rules from each of the participating forests.  Since we are using existing information, I do not think a legal review is necessary.
Also, all of the requirements for the permit are existing for special forest products permits now (fill out the month and day, track how many have been removed, have it with you, nontransferable).  The only one that comes to mind that is different is the one that requests them to place on dashboard (vs. having with them, or putting a tag on a product visible from other vehicles).  But even then, Forests can create conditions specific to their forests in the Other Conditions box of the TIM generated permit. To my knowledge this occurs without a forma legal review from say OMB or OGC.

**Comment by JaneZC** [comment]
@MelissaBraxton @ASprinkle I just wanted to be clear that I don't know the answers for this one, but did want to make sure to raise it. Sometimes, once lawyers review things, lots of follow-up 'fun' ensues with text changes and, in some instances design so I figured it best to flag it so it doesn't get overlooked. :)

**Comment by ASprinkle** [comment]
Sounds good @ @JaneZC. It looks like TTS has it in their backlog, and will be addressing it later.

**Comment by ASprinkle** [comment]
Closing - this story is being addressed through multiple stories in Sprint 10 that restructure the information and rules pages.
